name: env_labels
channels:
  - conda-forge
  - defaults
  - terradue
dependencies:
  - pystac>=1.4.0
  - python >=3.6
  - numpy
  - gdal
  - shapely
  - scikit-learn
  - scikit-image
  - ipykernel
  - pandas
  # - click2cwl
  # - matplotlib
  # - scipy
  # - rasterio